<a href="https://colab.research.google.com/github/Belva99/valuarte99/blob/main/ejercicioLeccionNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Create a 1D array of numbers from 0 to 9
# your code here
import numpy as np

pass

In [25]:
# Create random vector of size 10 and replace the maximum value by 0lista=list(range(9))
# Create a random vector of size 10
x = np.random.random(10)

# Print the original vector
print("Original vector:")
print(x)

# Find the index of the maximum value
max_index = x.argmax()

# Replace the maximum value by 0
x[max_index] = 0

# Print the modified vector
print("Modified vector:")
print(x)

Original vector:
[0.06601481 0.82658316 0.58073187 0.11206337 0.8456325  0.59462112
 0.67325349 0.0593629  0.03907248 0.11493683]
Modified vector:
[0.06601481 0.82658316 0.58073187 0.11206337 0.         0.59462112
 0.67325349 0.0593629  0.03907248 0.11493683]


In [3]:
vector = np.random.rand(10)
vector[vector.argmax()] = 0
print(vector)

pass

[0.70894598 0.73572025 0.11005579 0.47968008 0.17827401 0.
 0.18589075 0.3298024  0.70516689 0.05924888]


In [4]:
# Print the number 8 from the array below:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])

pass

8


In [5]:
# Print the numbers [3, 4, 5] from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])
pass

[3 4 5]


In [6]:
# Print the last 4 numbers from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[3:])
pass

[4 5 6 7]


In [7]:

# Create a 3×3 numpy array of all True’s
tmp=10*np.random.random((4,4))
mascara=tmp>0
print(tmp)
print("-------------------")
print(mascara)
pass

[[3.48365086 4.56371292 5.37151721 8.27669312]
 [3.05352663 1.80247471 1.36604179 0.69516659]
 [8.53005947 4.28040799 7.32668176 2.38260894]
 [4.04620982 1.07561281 1.05807453 9.65368252]]
-------------------
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [8]:
# Extract all odd numbers from arr
tmp = np.random.randint(1, 11, size=(4, 4))
print(tmp)

print('----------------------------------')

mask = np.mod(tmp, 2) == 0
print(tmp[mask])
pass


[[ 2  2  3  2]
 [ 7  9  9  9]
 [10  7  4  5]
 [ 9  3  8  8]]
----------------------------------
[ 2  2  2 10  4  8  8]


In [9]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
tmp = np.arange(10,50)
print(tmp)
pass

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
# Reverse a vector (first element becomes last)
vectorInvertido = tmp[::-1]
print(vectorInvertido)
pass

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
tmp = np.random.randint(1, 101, size=(10, 10))
minimo = np.min(tmp)
maximo = np.max(tmp)
print("Matriz")
print(tmp)
print("Minimo")
print(minimo)
print("Maximo")
print(maximo)
pass

Matriz
[[74 57 51 27 63 66 97 49  7 63]
 [17 45 85 51 85 91 59 29 19 71]
 [71 81 76 17 14 69 53 86 30 21]
 [30 26 92 42 66 18 51 94 37 67]
 [26 57 88 27 91 52 99 32 29 84]
 [83 76  3 93 77 88 29  2 44 61]
 [11 57  3 26 92 59 80  7 86  2]
 [20 29 81  2 34 69 23 19 92 41]
 [42 90 38 41 85 38 62 51 12  1]
 [10 43 30 27  8 60 45 63 58 48]]
Minimo
1
Maximo
99


In [12]:
# Create a 3x3x3 array with random values
tmp2 = np.random.random((3,3,3))
print(tmp2)
pass

[[[0.7955613  0.76308668 0.04574854]
  [0.45864819 0.77888808 0.88046418]
  [0.04616754 0.95435645 0.09680812]]

 [[0.87564521 0.87960478 0.47733531]
  [0.2013573  0.29123922 0.30956874]
  [0.36484368 0.61414305 0.71526659]]

 [[0.44099729 0.27163526 0.5303793 ]
  [0.97198759 0.74995924 0.78538303]
  [0.22008486 0.99817693 0.2479018 ]]]


In [13]:
# Replace all odd numbers in arr with -1
tmp = np.random.randint(1, 11, size=(3, 3, 3))
print(tmp)
print("-----------------")
tmp[tmp % 2 == 1] = -1
print(tmp)
pass

[[[ 9 10 10]
  [10 10  8]
  [ 7  5 10]]

 [[ 4  5 10]
  [10  2  5]
  [ 7  4  5]]

 [[ 4  7 10]
  [ 7  7  3]
  [ 7  2  7]]]
-----------------
[[[-1 10 10]
  [10 10  8]
  [-1 -1 10]]

 [[ 4 -1 10]
  [10  2 -1]
  [-1  4 -1]]

 [[ 4 -1 10]
  [-1 -1 -1]
  [-1  2 -1]]]


In [14]:
# Create an array of type float
tmpF = np.random.rand(5)
print(tmpF)
pass

[0.38302531 0.92396871 0.49286667 0.12345946 0.43399813]


In [15]:
# Convert a 1D array to a 2D array with 2 rows
lista = list(range(12))
lista = np.array(lista)
two_d_array = lista.reshape(2, 6)
print(two_d_array)

pass


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [16]:
# How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
valoresComunes = np.intersect1d(Z1, Z2)
print(Z1)
print("-------------")
print(Z2)
print("-------------")
print(valoresComunes)
pass


[4 3 7 1 8 3 9 3 2 9]
-------------
[6 6 9 4 9 9 5 7 0 9]
-------------
[4 7 9]


In [17]:
#  Consider two random array A and B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print('Array A')
print(A)
print('Array B')
print(B)

if np.array_equal(A,B):
  print('Son iguales')
else:
  print('Son diferentes')

pass

Array A
[1 1 1 0 0]
Array B
[0 0 0 0 0]
Son diferentes


In [18]:
# Stack arrays a and b vertically
print('Array A')
print(A)
print('Array B')
print(B)
matrizApiladaVertical = np.vstack((A, B))
print("Stacked Array:")
print(matrizApiladaVertical)
pass

Array A
[1 1 1 0 0]
Array B
[0 0 0 0 0]
Stacked Array:
[[1 1 1 0 0]
 [0 0 0 0 0]]


In [19]:
# Stack the arrays a and b horizontally.
print('Array A')
print(A)
print('Array B')
print(B)
matrizApiladaHorizontal = np.hstack((A, B))
print("Stacked Array:")
print(matrizApiladaHorizontal)
pass

Array A
[1 1 1 0 0]
Array B
[0 0 0 0 0]
Stacked Array:
[1 1 1 0 0 0 0 0 0 0]


In [20]:
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)
print(tmp)
print('-------------')
valores = tmp[(tmp>=5)&(tmp<=10)]
print(valores)
# pass

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
-------------
[ 5  6  7  8  9 10]


In [21]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


"""Arrays"""
# a = np.array([5, 7, 9, 8, 6, 4, 5])
a = np.random.randint(1,10,7)
print("Array A")
print(a)
# b = np.array([6, 3, 4, 8, 9, 7, 1])
b = np.random.randint(1,10,7)
print("Array B")
print(b)

print("----------------------------")

"""Method 1"""
print("Method 1")
def parMax(a, b):
    """Get the element-wise maximum of two arrays"""
    return np.maximum(a, b)

c = parMax(a, b)
print(c)

print("----------------------------")

print("Method 2")
"""Method 2"""
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

c = np.array([maxx(x, y) for x, y in zip(a, b)])
print(c)

Array A
[5 6 6 9 3 8 6]
Array B
[8 5 4 7 7 8 3]
----------------------------
Method 1
[8 6 6 9 7 8 6]
----------------------------
Method 2
[8 6 6 9 7 8 6]


In [22]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)

# Swap columns 1 and 2
arr[:, [0, 1]] = arr[:, [1, 0]]

print("------------------------")
print("Cambio de columnas 1 y 2")
print(arr)

pass

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------------------
Cambio de columnas 1 y 2
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [23]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

random_array = np.random.uniform(5, 10, size=(5, 3))
print(random_array)


[[7.74435557 6.67910238 9.97723358]
 [6.51038888 5.2264682  5.03998993]
 [5.46156898 8.05465527 8.26783803]
 [9.64044084 8.53237835 6.6489088 ]
 [6.79966672 9.0406004  9.81828751]]
