<a href="https://colab.research.google.com/github/Belva99/valuarte99/blob/main/PracticeNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.random.randint(1,11,size=(3,4))
b=np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print('adding numbers')
print(a+b)
print('substracting numbers')
print(a-b)
print('multiply numbers')
print(a*b)

print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 1  2 10  5]
 [ 9  3  2  3]
 [ 6  3 10  6]]
[[10  7  4  2]
 [ 2  8  4  3]
 [ 3  6  5  1]]
(3, 4)
(3, 4)
adding numbers
[[11  9 14  7]
 [11 11  6  6]
 [ 9  9 15  7]]
substracting numbers
[[-9 -5  6  3]
 [ 7 -5 -2  0]
 [ 3 -3  5  5]]
multiply numbers
[[10 14 40 10]
 [18 24  8  9]
 [18 18 50  6]]
[[11  9 14  7]
 [11 11  6  6]
 [ 9  9 15  7]]
[[10 14 40 10]
 [18 24  8  9]
 [18 18 50  6]]
[[0.1        0.28571429 2.5        2.5       ]
 [4.5        0.375      0.5        1.        ]
 [2.         0.5        2.         6.        ]]


In [2]:
a=np.random.randint(1,11,size=(2,3))
b=np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(np.dot(a,b))
print(a.dot(b))

[[2 7 4]
 [5 6 8]]
[[ 6  5  4  1]
 [ 1 10  6 10]
 [ 4  2  3  5]]
[[ 35  88  62  92]
 [ 68 101  80 105]]
[[ 35  88  62  92]
 [ 68 101  80 105]]


In [3]:
a=np.random.randint(1,11,size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[9 6]
 [4 9]]
[[9 4]
 [6 9]]


In [4]:
a=np.random.randint(1,11,size=(4,3))
b=np.array([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(a)
print(b)
print(c.shape)
print('------------------')
print(c)



(4, 3)
(3,)
[[10  7  7]
 [ 4  4  5]
 [ 7  6  8]
 [ 6  2  4]]
[1 0 2]
(4, 3)
------------------
[[ 1  2 10]
 [ 5  9  3]
 [ 2  3  6]
 [ 3 10  6]]


In [5]:
for i in range(4):
  c[i,:]=a[i,:]+b

print(a)
print(b)
print(c)
print('------------------')
c=a+b
print(c)

[[10  7  7]
 [ 4  4  5]
 [ 7  6  8]
 [ 6  2  4]]
[1 0 2]
[[11  7  9]
 [ 5  4  7]
 [ 8  6 10]
 [ 7  2  6]]
------------------
[[11  7  9]
 [ 5  4  7]
 [ 8  6 10]
 [ 7  2  6]]


In [6]:
a=np.array([1,2,3])


#print(a)


tmp=np.tile(a,(6,1))
print(tmp)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [7]:
matriz = np.random.randint(0, 10, size=(6, 6))
print(matriz)

aux=np.mean(matriz)
print(aux)
print('------------------')
matriz = np.random.randint(0, 10, size=(6, 6))
print(matriz)
print('------------------')
promedio_por_filas = np.mean(matriz, axis=1)
print("\nEl promedio por filas de la matriz es:")
print(promedio_por_filas)

[[2 8 8 5 1 3]
 [9 1 2 5 3 2]
 [7 5 0 8 6 7]
 [5 8 1 6 1 7]
 [3 9 4 3 9 6]
 [2 5 1 3 2 7]]
4.555555555555555
------------------
[[8 1 4 8 2 8]
 [3 0 9 2 3 3]
 [2 9 5 7 6 5]
 [2 3 7 4 4 4]
 [6 5 2 4 7 9]
 [2 2 7 8 6 4]]
------------------

El promedio por filas de la matriz es:
[5.16666667 3.33333333 5.66666667 4.         5.5        4.83333333]


In [13]:
# Operaciones de arrays
arr_a = np.array([2, 4, 6])
arr_b = np.array([1, 2, 3])

# Suma y resta de arrays
sum_result = arr_a + arr_b
difference_result = arr_a - arr_b

print("Suma de arrays:", sum_result)
print("Resta de arrays:", difference_result)

# Multiplicación y división de arrays
product_result = arr_a * arr_b
division_result = arr_a / arr_b

print("Multiplicación de arrays:", product_result)
print("División de arrays:", division_result)

Suma de arrays: [3 6 9]
Resta de arrays: [1 2 3]
Multiplicación de arrays: [ 2  8 18]
División de arrays: [2. 2. 2.]


In [14]:
# Operaciones estadísticas básicas
data = np.array([5, 8, 12, 15, 20])

# Media y mediana
mean_value = np.mean(data)
median_value = np.median(data)

print("Media:", mean_value)
print("Mediana:", median_value)

Media: 12.0
Mediana: 12.0


In [15]:
# Broadcasting con arrays de diferentes dimensiones
arr_2d = np.array([[3, 4, 5], [6, 7, 8]])
arr_1d = np.array([10, 20, 30])
result_broadcasting = arr_2d + arr_1d

print("Resultado del Broadcasting:")
print(result_broadcasting)

# Reshape de arrays
reshaped_arr = arr_1d.reshape((3, 1))

print("\nArray Reshape:")
print(reshaped_arr)

# Concatenación de arrays a lo largo de diferentes ejes
arr_a = np.array([[3, 4], [5, 6]])
arr_b = np.array([[7, 8]])
concatenated_arr = np.concatenate((arr_a, arr_b.T), axis=1)

print("\nResultado de la Concatenación:")
print(concatenated_arr)

Resultado del Broadcasting:
[[13 24 35]
 [16 27 38]]

Array Reshape:
[[10]
 [20]
 [30]]

Resultado de la Concatenación:
[[3 4 7]
 [5 6 8]]
